[tool.poetry]
name = "root"
version = "0"
description = ""
authors = ["Kiran Gadhave <kirangadhave2@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
jupyterlab = "^3.5.2"
jupyter-packaging = "^0.12.3"
panel = "^0.14.2"
tornado = "^6.2"
altair = "^4.2.2"
pandas = "^1.5.3"
numpy = "^1.24.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
