# a mybinder.org-ready environment for demoing persist_ext
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate persist-ext-demo
#
name: persist-ext-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python>=3.11
  - jupyterlab>=4.0.0
  - pip
  - pip:
      - persist_ext
